-- Inserción de datos en la tabla DIAGNOSTICO con el atributo Tipo
INSERT INTO DIAGNOSTICO (Descripcion, Tipo) VALUES
('Labor de parto', 'Crítico'),
('Parto normal', 'Normal'),
('Parto normal/obito fetal', 'Crítico'),
('Parto cesarea', 'Normal'),
('Parto cesarea/obito fetal', 'Crítico'),
('Sufrimiento fetal', 'Crítico'),
('Desproporción C/P', 'Crítico'),
('Pre eclampsia', 'Crítico'),
('Presentación podálica', 'Crítico'),
('Inducción fallida', 'Crítico'),
('Hemorragia tercer trimestre', 'Crítico'),
('Distocia dinámica', 'Crítico'),
('Embarazo Normal', 'Normal'),
('Embarazo de Alto Riesgo', 'Alto Riesgo'),
('Eclampsia', 'Crítico'),
('Abortos Espontáneos', 'Crítico'),
('Parto Prematuro', 'Alto Riesgo'),
('Placenta Previa', 'Crítico'),
('Ginecomastia', 'Normal'),
('Infección de Vías Urinarias', 'Moderado'),
('Síndrome de Ovario Poliquístico', 'Moderado'),
('Endometriosis', 'Crónico'),
('Miomas Uterinos', 'Crónico'),
('Cáncer de Mama', 'Crítico'),
('Cáncer de Cérvix', 'Crítico'),
('Infecciones de Transmisión Sexual', 'Moderado'),
('Hiperemesis Gravidarum', 'Moderado'),
('Diabetes Gestacional', 'Alto Riesgo'),
('Desgarros Perineales', 'Moderado'),
('Hemorroides', 'Moderado'),
('Anemia Ferropénica', 'Moderado'),
('Fibromas Uterinos', 'Crónico'),
('Mastitis', 'Moderado'),
('Cáncer de Ovario', 'Crítico'),
('Síndrome de Turner', 'Moderado'),
('Trastornos Menstruales', 'Moderado'),
('Hiperplasia Endometrial', 'Moderado'),
('Quiste Ovárico', 'Moderado'),
('Oligomenorrea', 'Moderado'),
('Amenorrea', 'Moderado');
