
INSERT INTO ESPECIALIDAD (Nombre) VALUES
('Ginecología General'),
('Obstetricia'),
('Fertilidad'),
('Salud Reproductiva'),
('Cirugía Ginecológica'),
('Endocrinología Ginecológica'),
('Ginecología Oncológica'),
('Medicina Materno-Fetal'),
('Ginecología Pediátrica'),
('Ginecología Urológica'),
('Uroginecología'),
('Planificación Familiar'),
('Laparoscopia Ginecológica'),
('Colposcopia'),
('Sexología Clínica'),
('Patología Cervical'),
('Ecografía Ginecológica'),
('Medicina Reproductiva'),
('Oncología Ginecológica'),
('Patología Mamaria'),
('Medicina Prenatal'),
('Diagnóstico Prenatal'),
('Terapia Hormonal'),
('Medicina Regenerativa'),
('Inseminación Artificial'),
('Fecundación In Vitro'),
('Tratamiento de Menopausia'),
('Desórdenes Menstruales'),
('Endometriosis'),
('Miomas Uterinos'),
('Infertilidad Masculina'),
('Embriología Clínica'),
('Cuidado Neonatal'),
('Terapia Genética Reproductiva'),
('Biopsia Ginecológica'),
('Tratamiento de VPH'),
('Cirugía Robótica Ginecológica'),
('Manejo del Dolor Obstétrico'),
('Anestesia Obstétrica'),
('Cuidados Intensivos Neonatales'),
('Terapia del Suelo Pélvico'),
('Terapia Física Pélvica'),
('Patología Vulvar'),
('Oncología Reproductiva'),
('Histeroscopia'),
('Terapia de Fecundación'),
('Genética Prenatal'),
('Cardiología Obstétrica'),
('Medicina Perinatal'),
('Cirugía Mínimamente Invasiva');
