
INSERT INTO HOSPITAL (CasaAtencion) VALUES
('Hospital Edgardo Rebagliati'),
('Hospital Guillermo Almenara'),
('Hospital Alberto Sabogal'),
('Hospital Nacional Víctor Lazarte'),
('Hospital Nacional Ramiro Prialé'),
('Hospital Nacional Carlos Alcántara'),
('Hospital I La Merced'),
('Hospital II Suárez Angamos'),
('Policlínico Chincha'),
('Hospital I Octavio Mongrut'),
('Policlínico Pablo Bermúdez'),
('Hospital Jorge Voto Bernales'),
('Policlínico Grau'),
('Hospital I Cañete'),
('Hospital I Tarapoto'),
('Hospital II Cajamarca'),
('Hospital III Puno'),
('Hospital I Huacho'),
('Hospital I Huaraz'),
('Policlínico San Juan de Lurigancho'),
('Hospital III Iquitos'),
('Hospital II Vitarte'),
('Hospital I Ilo'),
('Hospital II Arequipa'),
('Policlínico Metropolitano Piura'),
('Policlínico Tumbes'),
('Hospital II Huánuco'),
('Hospital I Moyobamba'),
('Policlínico Trujillo'),
('Hospital III Juliaca');
