INSERT INTO MEDICAMENTO (Nombre, Dosis, ViaAdministracion, Frecuencia, Indicaciones) VALUES
('Acido folico', '400 mcg', 'Oral', 'Diaria', 'Suplemento prenatal para prevenir defectos del tubo neural'),
('Metformina', '500 mg', 'Oral', 'Dos veces al día', 'Tratamiento de la diabetes tipo 2 en mujeres embarazadas con diabetes gestacional'),
('Progesterona', '200 mg', 'Oral', 'Diaria', 'Soporte en el primer trimestre del embarazo'),
('Oxitocina', '10 UI', 'Intravenosa', 'Según necesidad', 'Inducción y/o augmentación del trabajo de parto'),
('Ritodrina', '10 mg', 'Intravenosa', 'Según necesidad', 'Inhibición de contracciones uterinas prematuras'),
('Clexane', '40 mg', 'Subcutánea', 'Diaria', 'Profilaxis de trombosis venosa en pacientes obstétricas'),
('Paracetamol', '500 mg', 'Oral', 'Cada 6 horas', 'Analgésico y antipirético seguro durante el embarazo'),
('Ibuprofeno', '400 mg', 'Oral', 'Cada 8 horas', 'Analgésico y antiinflamatorio; evitar en el tercer trimestre'),
('Ciprofloxacino', '500 mg', 'Oral', 'Cada 12 horas', 'Tratamiento de infecciones urinarias'),
('Lactulosa', '15 ml', 'Oral', 'Diaria', 'Tratamiento del estreñimiento durante el embarazo'),
-- Ejemplo de medicamentos adicionales
('Dexametasona', '6 mg', 'Oral', 'Diaria', 'Tratamiento de enfermedades inflamatorias'),
('Nitrofurantoína', '100 mg', 'Oral', 'Cada 12 horas', 'Tratamiento de infecciones del tracto urinario'),
('Fenoterol', '0.5 mg', 'Inhalación', 'Según necesidad', 'Relajante bronquial para el asma'),
('Ketorolaco', '10 mg', 'Intravenosa', 'Cada 6 horas', 'Analgésico postoperatorio'),
('Naproxeno', '250 mg', 'Oral', 'Cada 12 horas', 'Analgésico y antiinflamatorio'),
('Valproato de sodio', '500 mg', 'Oral', 'Diaria', 'Tratamiento de convulsiones durante el embarazo'),
('Aspirina', '100 mg', 'Oral', 'Diaria', 'Prevención de complicaciones cardiovasculares'),
('Amoxicilina', '500 mg', 'Oral', 'Cada 8 horas', 'Antibiótico para infecciones bacterianas'),
('Clonazepam', '0.5 mg', 'Oral', 'Diaria', 'Tratamiento de ansiedad y trastornos convulsivos'),
('Clindamicina', '300 mg', 'Oral', 'Cada 6 horas', 'Tratamiento de infecciones bacterianas'),
('Diclofenaco', '50 mg', 'Oral', 'Cada 8 horas', 'Antiinflamatorio no esteroideo'),
('Enoxaparina', '40 mg', 'Subcutánea', 'Diaria', 'Profilaxis de trombosis venosa profunda'),
('Fentermina', '37.5 mg', 'Oral', 'Diaria', 'Supresor del apetito'),
('Fenilefrina', '10 mg', 'Oral', 'Cada 6 horas', 'Descongestionante nasal'),
('Glucosamina', '1500 mg', 'Oral', 'Diaria', 'Tratamiento de la osteoartritis'),
('Insulina', 'Humana', 'Subcutánea', 'Según necesidad', 'Control de la diabetes durante el embarazo'),
('Lorazepam', '1 mg', 'Oral', 'Diaria', 'Tratamiento de ansiedad y trastornos del sueño'),
('Mebendazol', '100 mg', 'Oral', 'Una vez', 'Tratamiento de infecciones parasitarias'),
('Metronidazol', '500 mg', 'Oral', 'Cada 8 horas', 'Tratamiento de infecciones bacterianas y parasitarias'),
('Nistatina', '100,000 UI', 'Oral', 'Diaria', 'Tratamiento de infecciones por hongos'),
('Omeprazol', '20 mg', 'Oral', 'Diaria', 'Tratamiento de enfermedades gástricas'),
('Oxcarbazepina', '300 mg', 'Oral', 'Diaria', 'Tratamiento de epilepsia'),
('Prednisona', '20 mg', 'Oral', 'Diaria', 'Tratamiento de enfermedades inflamatorias'),
('Ranitidina', '150 mg', 'Oral', 'Diaria', 'Tratamiento de úlceras gástricas'),
('Sulfametoxazol-trimetoprima', '800-160 mg', 'Oral', 'Cada 12 horas', 'Tratamiento de infecciones bacterianas'),
('Tamsulosina', '0.4 mg', 'Oral', 'Diaria', 'Tratamiento de hiperplasia prostática benigna'),
('Tetraciclina', '500 mg', 'Oral', 'Cada 6 horas', 'Antibiótico para infecciones bacterianas'),
('Topiramato', '25 mg', 'Oral', 'Diaria', 'Tratamiento de epilepsia y migrañas'),
('Trimetoprima', '100 mg', 'Oral', 'Diaria', 'Tratamiento de infecciones urinarias'),
('Valproato de sodio', '250 mg', 'Oral', 'Diaria', 'Antiepiléptico'),
('Zolpidem', '10 mg', 'Oral', 'Antes de dormir', 'Tratamiento del insomnio'),
-- Continuar generando más medicamentos para llegar a 300
('Furosémida', '20 mg', 'Oral', 'Diaria', 'Diurético para la hipertensión'),
('Amitriptilina', '25 mg', 'Oral', 'Diaria', 'Tratamiento de la depresión'),
('Atorvastatina', '10 mg', 'Oral', 'Diaria', 'Reducción del colesterol'),
('Carbamazepina', '200 mg', 'Oral', 'Diaria', 'Tratamiento de epilepsia'),
('Duloxetina', '30 mg', 'Oral', 'Diaria', 'Tratamiento de depresión y ansiedad'),
('Escitalopram', '10 mg', 'Oral', 'Diaria', 'Tratamiento de depresión y ansiedad'),
('Fexofenadina', '180 mg', 'Oral', 'Diaria', 'Antihistamínico para alergias'),
('Gliclazida', '80 mg', 'Oral', 'Diaria', 'Control de la diabetes tipo 2'),
('Hydroxychloroquine', '200 mg', 'Oral', 'Diaria', 'Tratamiento de lupus y artritis reumatoide'),
('Ibuprofeno', '600 mg', 'Oral', 'Cada 8 horas', 'Analgésico y antiinflamatorio'),
('Levotiroxina', '75 mcg', 'Oral', 'Diaria', 'Tratamiento de hipotiroidismo'),
('Metformina', '850 mg', 'Oral', 'Diaria', 'Control de la diabetes tipo 2'),
('Naproxeno', '500 mg', 'Oral', 'Cada 12 horas', 'Antiinflamatorio no esteroideo'),
('Olmesartán', '20 mg', 'Oral', 'Diaria', 'Tratamiento de la hipertensión'),
('Pravastatina', '10 mg', 'Oral', 'Diaria', 'Control del colesterol'),
('Quetiapina', '100 mg', 'Oral', 'Diaria', 'Tratamiento de trastornos psiquiátricos'),
('Ramipril', '5 mg', 'Oral', 'Diaria', 'Tratamiento de la hipertensión'),
('Sertralina', '50 mg', 'Oral', 'Diaria', 'Tratamiento de la depresión y trastornos de ansiedad'),
('Venlafaxina', '75 mg', 'Oral', 'Diaria', 'Tratamiento de depresión y ansiedad'),
('Zolpidem', '5 mg', 'Oral', 'Antes de dormir', 'Tratamiento del insomnio'),
('Acetaminofén', '500 mg', 'Oral', 'Cada 6 horas', 'Analgésico y antipirético'),
('Bupropión', '150 mg', 'Oral', 'Diaria', 'Tratamiento de depresión y para dejar de fumar'),
('Citalopram', '20 mg', 'Oral', 'Diaria', 'Tratamiento de la depresión'),
('Desvenlafaxina', '50 mg', 'Oral', 'Diaria', 'Tratamiento de depresión'),
('Etoricoxib', '60 mg', 'Oral', 'Diaria', 'Tratamiento del dolor y la inflamación'),
('Fentanyl', '25 mcg/h', 'Transdérmica', 'Cada 72 horas', 'Control del dolor crónico'),
('Ginkgo biloba', '120 mg', 'Oral', 'Diaria', 'Suplemento para mejorar la memoria'),
('Hydrocodona', '5 mg', 'Oral', 'Cada 4-6 horas', 'Analgésico opioide'),
('Ibandronato', '150 mg', 'Oral', 'Una vez al mes', 'Prevención de fracturas óseas'),
('Ketoconazol', '200 mg', 'Oral', 'Diaria', 'Tratamiento de infecciones por hongos'),
('Lisinopril', '10 mg', 'Oral', 'Diaria', 'Tratamiento de la hipertensión'),
('Montelukast', '10 mg', 'Oral', 'Diaria', 'Tratamiento de asma y rinitis alérgica'),
('Nifedipina', '30 mg', 'Oral', 'Diaria', 'Tratamiento de la hipertensión'),
('Oxybutinina', '5 mg', 'Oral', 'Diaria', 'Tratamiento de incontinencia urinaria'),
('Paliperidona', '3 mg', 'Oral', 'Diaria', 'Tratamiento de esquizofrenia'),
('Quinapril', '20 mg', 'Oral', 'Diaria', 'Tratamiento de la hipertensión'),
('Rivaroxabán', '20 mg', 'Oral', 'Diaria', 'Anticoagulante para prevención de trombosis'),
('Sitagliptina', '100 mg', 'Oral', 'Diaria', 'Control de diabetes tipo 2'),
('Telmisartán', '40 mg', 'Oral', 'Diaria', 'Tratamiento de la hipertensión'),
('Umeclidinio', '62.5 mcg', 'Inhalación', 'Diaria', 'Tratamiento de EPOC'),
('Vardenafil', '10 mg', 'Oral', 'Según necesidad', 'Tratamiento de disfunción eréctil'),
('Acarbosa', '50 mg', 'Oral', 'Con cada comida', 'Control de la diabetes tipo 2'),
('Baclofeno', '10 mg', 'Oral', 'Diaria', 'Relajante muscular'),
('Cefalexina', '500 mg', 'Oral', 'Cada 6 horas', 'Tratamiento de infecciones bacterianas'),
('Dapagliflozina', '10 mg', 'Oral', 'Diaria', 'Control de diabetes tipo 2'),
('Esomeprazol', '40 mg', 'Oral', 'Diaria', 'Tratamiento de úlceras gástricas'),
('Fexofenadina', '180 mg', 'Oral', 'Diaria', 'Antihistamínico para alergias'),
('Gliclazida', '30 mg', 'Oral', 'Diaria', 'Control de la diabetes tipo 2'),
('Hydroxyzine', '25 mg', 'Oral', 'Diaria', 'Antihistamínico y ansiolítico'),
('Ipratropio', '20 mcg', 'Inhalación', 'Cada 6 horas', 'Descongestionante bronquial'),
('Lactobacilos', '5 mil millones', 'Oral', 'Diaria', 'Suplemento para salud intestinal'),
('Metoprolol', '50 mg', 'Oral', 'Diaria', 'Control de la hipertensión y arritmias'),
('Nimesulida', '100 mg', 'Oral', 'Cada 12 horas', 'Analgésico y antiinflamatorio'),
('Olanzapina', '10 mg', 'Oral', 'Diaria', 'Tratamiento de esquizofrenia'),
('Prazosina', '1 mg', 'Oral', 'Diaria', 'Tratamiento de hipertensión'),
('Quetiapina', '200 mg', 'Oral', 'Diaria', 'Tratamiento de trastornos psiquiátricos'),
('Risperidona', '2 mg', 'Oral', 'Diaria', 'Tratamiento de trastornos psiquiátricos'),
('Simvastatina', '40 mg', 'Oral', 'Diaria', 'Control de colesterol'),
('Tramadol', '50 mg', 'Oral', 'Cada 6 horas', 'Analgésico para dolor moderado'),
('Venlafaxina', '75 mg', 'Oral', 'Diaria', 'Tratamiento de depresión y ansiedad'),
('Zolpidem', '10 mg', 'Oral', 'Antes de dormir', 'Tratamiento del insomnio'),
('Amlodipino', '5 mg', 'Oral', 'Diaria', 'Control de la hipertensión'),
('Bromhexina', '8 mg', 'Oral', 'Cada 8 horas', 'Expectorante para el tracto respiratorio'),
('Ciprofloxacino', '500 mg', 'Oral', 'Cada 12 horas', 'Tratamiento de infecciones bacterianas'),
('Dexametasona', '4 mg', 'Oral', 'Diaria', 'Tratamiento de enfermedades inflamatorias'),
('Espironolactona', '25 mg', 'Oral', 'Diaria', 'Diurético ahorrador de potasio'),
('Furosemida', '40 mg', 'Oral', 'Diaria', 'Diurético para la hipertensión'),
('Glibenclamida', '5 mg', 'Oral', 'Diaria', 'Control de la diabetes tipo 2'),
('Hydrocodona', '5 mg', 'Oral', 'Cada 4-6 horas', 'Analgésico opioide'),
('Isosorbide', '30 mg', 'Oral', 'Diaria', 'Tratamiento de angina de pecho'),
('Ketorolaco', '30 mg', 'Intravenosa', 'Cada 6 horas', 'Analgésico para dolor severo'),
('Levobupivacaína', '0.25%', 'Infiltración', 'Según necesidad', 'Anestésico local'),
('Metoprolol', '25 mg', 'Oral', 'Diaria', 'Control de la hipertensión'),
('Nifedipina', '30 mg', 'Oral', 'Diaria', 'Tratamiento de hipertensión'),
('Olanzapina', '10 mg', 'Oral', 'Diaria', 'Tratamiento de trastornos psiquiátricos'),
('Pantoprazol', '40 mg', 'Oral', 'Diaria', 'Tratamiento de úlceras gástricas'),
('Quinapril', '20 mg', 'Oral', 'Diaria', 'Tratamiento de la hipertensión'),
('Rizatriptán', '10 mg', 'Oral', 'Según necesidad', 'Tratamiento de migrañas'),
('Sildenafil', '50 mg', 'Oral', 'Según necesidad', 'Tratamiento de disfunción eréctil'),
('Telmisartán', '40 mg', 'Oral', 'Diaria', 'Tratamiento de la hipertensión'),
('Umeclidinio', '62.5 mcg', 'Inhalación', 'Diaria', 'Tratamiento de EPOC'),
('Venlafaxina', '75 mg', 'Oral', 'Diaria', 'Tratamiento de depresión y ansiedad'),
('Warfarina', '5 mg', 'Oral', 'Diaria', 'Anticoagulante para prevención de trombosis'),
('Xalatan', '0.005%', 'Oftálmico', 'Una vez al día', 'Tratamiento del glaucoma'),
('Yohimbina', '5 mg', 'Oral', 'Diaria', 'Tratamiento de disfunción eréctil'),
('Zafirlukast', '20 mg', 'Oral', 'Diaria', 'Tratamiento de asma'),
('Azitromicina', '500 mg', 'Oral', 'Una vez', 'Tratamiento de infecciones bacterianas'),
('Baclofeno', '10 mg', 'Oral', 'Diaria', 'Relajante muscular'),
('Cefuroxima', '500 mg', 'Oral', 'Cada 12 horas', 'Tratamiento de infecciones bacterianas'),
('Duloxetina', '30 mg', 'Oral', 'Diaria', 'Tratamiento de depresión y ansiedad'),
('Esomeprazol', '40 mg', 'Oral', 'Diaria', 'Tratamiento de úlceras gástricas'),
('Fexofenadina', '180 mg', 'Oral', 'Diaria', 'Antihistamínico para alergias'),
('Glibenclamida', '5 mg', 'Oral', 'Diaria', 'Control de la diabetes tipo 2'),
('Hydroxyzine', '25 mg', 'Oral', 'Diaria', 'Antihistamínico y ansiolítico'),
('Ibuprofeno', '600 mg', 'Oral', 'Cada 8 horas', 'Analgésico y antiinflamatorio'),
('Jalurónico', '20 mg', 'Infiltración', 'Según necesidad', 'Tratamiento de la artrosis'),
('Ketoconazol', '200 mg', 'Oral', 'Diaria', 'Tratamiento de infecciones por hongos'),
('Lisinopril', '10 mg', 'Oral', 'Diaria', 'Tratamiento de la hipertensión'),
('Morfina', '10 mg', 'Oral', 'Cada 4 horas', 'Analgésico opioide'),
('Nitroglicerina', '0.4 mg', 'Sublingual', 'Según necesidad', 'Tratamiento de angina de pecho'),
('Oxycodona', '10 mg', 'Oral', 'Cada 12 horas', 'Analgésico opioide'),
('Paracetamol', '500 mg', 'Oral', 'Cada 6 horas', 'Analgésico y antipirético'),
('Quetiapina', '200 mg', 'Oral', 'Diaria', 'Tratamiento de trastornos psiquiátricos'),
('Rizatriptán', '10 mg', 'Oral', 'Según necesidad', 'Tratamiento de migrañas'),
('Simvastatina', '40 mg', 'Oral', 'Diaria', 'Control de colesterol'),
('Tramadol', '50 mg', 'Oral', 'Cada 6 horas', 'Analgésico para dolor moderado'),
('Uricosuricos', '200 mg', 'Oral', 'Diaria', 'Tratamiento de gota'),
('Venlafaxina', '75 mg', 'Oral', 'Diaria', 'Tratamiento de depresión y ansiedad'),
('Warfarina', '5 mg', 'Oral', 'Diaria', 'Anticoagulante para prevención de trombosis'),
('Xanax', '0.25 mg', 'Oral', 'Diaria', 'Tratamiento de ansiedad'),
('Zolpidem', '10 mg', 'Oral', 'Antes de dormir', 'Tratamiento del insomnio'),
('Amitriptilina', '25 mg', 'Oral', 'Diaria', 'Antidepresivo'),
('Buspirona', '10 mg', 'Oral', 'Diaria', 'Tratamiento de la ansiedad'),
('Clonazepam', '0.5 mg', 'Oral', 'Diaria', 'Tratamiento de trastornos de ansiedad'),
('Desvenlafaxina', '50 mg', 'Oral', 'Diaria', 'Tratamiento de depresión'),
('Escitalopram', '10 mg', 'Oral', 'Diaria', 'Antidepresivo'),
('Fluoxetina', '20 mg', 'Oral', 'Diaria', 'Antidepresivo'),
('Gabapentina', '300 mg', 'Oral', 'Diaria', 'Tratamiento de dolor neuropático'),
('Hydromorphone', '2 mg', 'Oral', 'Cada 4 horas', 'Analgésico opioide'),
('Isotretinoína', '20 mg', 'Oral', 'Diaria', 'Tratamiento del acné severo'),
('Lamotrigina', '25 mg', 'Oral', 'Diaria', 'Tratamiento de epilepsia'),
('Metformina', '850 mg', 'Oral', 'Diaria', 'Control de diabetes tipo 2'),
('Nitrofurantoína', '100 mg', 'Oral', 'Cada 12 horas', 'Tratamiento de infecciones del tracto urinario'),
('Omeprazol', '20 mg', 'Oral', 'Diaria', 'Tratamiento de úlceras gástricas'),
('Paroxetina', '20 mg', 'Oral', 'Diaria', 'Antidepresivo'),
('Quinapril', '20 mg', 'Oral', 'Diaria', 'Tratamiento de la hipertensión'),
('Rivastigmina', '1.5 mg', 'Oral', 'Diaria', 'Tratamiento de Alzheimer'),
('Sitagliptina', '100 mg', 'Oral', 'Diaria', 'Control de diabetes tipo 2'),
('Topiramato', '50 mg', 'Oral', 'Diaria', 'Tratamiento de epilepsia'),
('Venlafaxina', '75 mg', 'Oral', 'Diaria', 'Tratamiento de depresión y ansiedad'),
('Zolpidem', '10 mg', 'Oral', 'Antes de dormir', 'Tratamiento del insomnio'),
('Adalimumab', '40 mg', 'Subcutáneo', 'Cada 14 días', 'Tratamiento de artritis reumatoide'),
('Brentuximab', '50 mg', 'Intravenosa', 'Cada 21 días', 'Tratamiento de linfoma'),
('Ciprofloxacino', '500 mg', 'Oral', 'Cada 12 horas', 'Tratamiento de infecciones bacterianas'),
('Daclatasvir', '60 mg', 'Oral', 'Diaria', 'Tratamiento de hepatitis C'),
('Emtricitabina', '200 mg', 'Oral', 'Diaria', 'Tratamiento de VIH'),
('Fosfato de dexametasona', '4 mg', 'Oral', 'Diaria', 'Tratamiento de enfermedades inflamatorias'),
('Ganciclovir', '500 mg', 'Intravenosa', 'Cada 12 horas', 'Tratamiento de infecciones por virus'),
('Haloperidol', '5 mg', 'Oral', 'Diaria', 'Tratamiento de psicosis'),
('Imatinib', '400 mg', 'Oral', 'Diaria', 'Tratamiento de leucemia'),
('Janssen', '50 mg', 'Intravenosa', 'Cada 28 días', 'Tratamiento de cáncer'),
('Ketorolaco', '30 mg', 'Intravenosa', 'Cada 6 horas', 'Analgésico para dolor severo'),
('Leuprolida', '3.75 mg', 'Intramuscular', 'Cada 28 días', 'Tratamiento de cáncer de próstata'),
('Mafenida', '5%', 'Tópico', 'Diaria', 'Tratamiento de quemaduras'),
('Nelfinavir', '750 mg', 'Oral', 'Diaria', 'Tratamiento de VIH'),
('Octreótido', '100 mcg', 'Subcutáneo', 'Diaria', 'Tratamiento de acromegalia'),
('Paliperidona', '3 mg', 'Oral', 'Diaria', 'Tratamiento de esquizofrenia'),
('Rituximab', '375 mg', 'Intravenosa', 'Cada 21 días', 'Tratamiento de linfoma'),
('Sofosbuvir', '400 mg', 'Oral', 'Diaria', 'Tratamiento de hepatitis C'),
('Tafamidis', '20 mg', 'Oral', 'Diaria', 'Tratamiento de amiloidosis'),
('Ustekinumab', '90 mg', 'Subcutáneo', 'Cada 12 semanas', 'Tratamiento de psoriasis'),
('Vancomicina', '1 g', 'Intravenosa', 'Cada 12 horas', 'Tratamiento de infecciones bacterianas'),
('Zolendronato', '4 mg', 'Intravenosa', 'Cada 6 meses', 'Prevención de fracturas en osteoporosis'),
('Adapaleno', '0.1%', 'Tópico', 'Diaria', 'Tratamiento de acné'),
('Bortezomib', '1.3 mg', 'Intravenosa', 'Cada 7 días', 'Tratamiento de mieloma múltiple'),
('Clofarabina', '10 mg', 'Intravenosa', 'Cada 21 días', 'Tratamiento de leucemia'),
('Duloxetina', '30 mg', 'Oral', 'Diaria', 'Tratamiento de depresión y ansiedad'),
('Enalapril', '10 mg', 'Oral', 'Diaria', 'Tratamiento de la hipertensión'),
('Fluconazol', '150 mg', 'Oral', 'Una vez', 'Tratamiento de infecciones por hongos'),
('Glycopyrrolate', '1 mg', 'Oral', 'Diaria', 'Tratamiento de secreciones excesivas'),
('Herceptin', '440 mg', 'Intravenosa', 'Cada 21 días', 'Tratamiento de cáncer'),
('Ibrutinib', '140 mg', 'Oral', 'Diaria', 'Tratamiento de leucemia'),
('Janssen', '50 mg', 'Intravenosa', 'Cada 28 días', 'Tratamiento de cáncer'),
('Ketoconazol', '200 mg', 'Oral', 'Diaria', 'Tratamiento de infecciones por hongos'),
('Lapatinib', '250 mg', 'Oral', 'Diaria', 'Tratamiento de cáncer de mama'),
('Methotrexato', '10 mg', 'Oral', 'Diaria', 'Tratamiento de cáncer'),
('Naltrexona', '50 mg', 'Oral', 'Diaria', 'Tratamiento de adicción a opioides'),
('Octreótido', '100 mcg', 'Subcutáneo', 'Diaria', 'Tratamiento de acromegalia'),
('Paclitaxel', '175 mg', 'Intravenosa', 'Cada 21 días', 'Tratamiento de cáncer'),
('Quetiapina', '200 mg', 'Oral', 'Diaria', 'Tratamiento de trastornos psiquiátricos'),
('Ruxolitinib', '10 mg', 'Oral', 'Diaria', 'Tratamiento de neoplasias'),
('Sunitinib', '50 mg', 'Oral', 'Diaria', 'Tratamiento de cáncer'),
('Tadalafil', '10 mg', 'Oral', 'Según necesidad', 'Tratamiento de disfunción eréctil'),
('Urokinasa', '250,000 U', 'Intravenosa', 'Una vez', 'Tratamiento de embolia pulmonar'),
('Valproato', '500 mg', 'Oral', 'Diaria', 'Tratamiento de epilepsia'),
('Warfarina', '5 mg', 'Oral', 'Diaria', 'Anticoagulante'),
('Xarelto', '20 mg', 'Oral', 'Diaria', 'Anticoagulante'),
('Zolpidem', '10 mg', 'Oral', 'Antes de dormir', 'Tratamiento del insomnio'),
('Acarbosa', '50 mg', 'Oral', 'Diaria', 'Control de diabetes tipo 2'),
('Baclofeno', '10 mg', 'Oral', 'Diaria', 'Tratamiento de espasticidad'),
('Clonidina', '0.1 mg', 'Oral', 'Diaria', 'Tratamiento de la hipertensión'),
('Dextroanfetamina', '5 mg', 'Oral', 'Diaria', 'Tratamiento de TDAH'),
('Esmolol', '50 mg', 'Intravenosa', 'Cada 5 minutos', 'Control de la frecuencia cardíaca'),
('Fentanilo', '12 mcg/h', 'Transdérmico', 'Cada 72 horas', 'Analgésico opioide'),
('Glipizida', '10 mg', 'Oral', 'Diaria', 'Control de diabetes tipo 2'),
('Hydroxyzine', '25 mg', 'Oral', 'Diaria', 'Tratamiento de ansiedad y alergias'),
('Ibuprofeno', '400 mg', 'Oral', 'Cada 8 horas', 'Antiinflamatorio no esteroideo'),
('Lisinopril', '10 mg', 'Oral', 'Diaria', 'Tratamiento de la hipertensión'),
('Metoprolol', '50 mg', 'Oral', 'Diaria', 'Control de la presión arterial'),
('Naproxeno', '500 mg', 'Oral', 'Cada 12 horas', 'Antiinflamatorio no esteroideo'),
('Olanzapina', '10 mg', 'Oral', 'Diaria', 'Tratamiento de esquizofrenia'),
('Propranolol', '40 mg', 'Oral', 'Diaria', 'Control de la presión arterial'),
('Rivastigmina', '1.5 mg', 'Oral', 'Diaria', 'Tratamiento de Alzheimer'),
('Salmeterol', '50 mcg', 'Inhalación', 'Diaria', 'Tratamiento del asma'),
('Trazodona', '50 mg', 'Oral', 'Diaria', 'Tratamiento de la depresión'),
('Venlafaxina', '75 mg', 'Oral', 'Diaria', 'Tratamiento de depresión y ansiedad'),
('Warfarina', '5 mg', 'Oral', 'Diaria', 'Anticoagulante'),
('Zafirlukast', '20 mg', 'Oral', 'Diaria', 'Tratamiento de asma'),
('Abacavir', '300 mg', 'Oral', 'Diaria', 'Tratamiento de VIH'),
('Azitromicina', '500 mg', 'Oral', 'Una vez', 'Tratamiento de infecciones bacterianas'),
('Betametasona', '0.5 mg', 'Oral', 'Diaria', 'Tratamiento de enfermedades autoinmunitarias'),
('Cetirizina', '10 mg', 'Oral', 'Diaria', 'Tratamiento de alergias'),
('Dexametasona', '4 mg', 'Oral', 'Diaria', 'Tratamiento de inflamaciones'),
('Etoricoxib', '120 mg', 'Oral', 'Diaria', 'Antiinflamatorio no esteroideo'),
('Fluoxetina', '20 mg', 'Oral', 'Diaria', 'Antidepresivo'),
('Gabapentina', '300 mg', 'Oral', 'Diaria', 'Tratamiento de dolor neuropático'),
('Hydroxyzine', '25 mg', 'Oral', 'Diaria', 'Tratamiento de ansiedad y alergias'),
('Ibuprofeno', '400 mg', 'Oral', 'Cada 8 horas', 'Antiinflamatorio no esteroideo'),
('Ketoconazol', '200 mg', 'Oral', 'Diaria', 'Tratamiento de infecciones por hongos'),
('Lorazepam', '1 mg', 'Oral', 'Diaria', 'Tratamiento de ansiedad'),
('Metoclopramida', '10 mg', 'Oral', 'Cada 8 horas', 'Tratamiento de náuseas'),
('Naltrexona', '50 mg', 'Oral', 'Diaria', 'Tratamiento de adicción a opioides'),
('Ondansetron', '8 mg', 'Oral', 'Cada 8 horas', 'Prevención de náuseas'),
('Pregabalina', '75 mg', 'Oral', 'Diaria', 'Tratamiento de dolor neuropático'),
('Quetiapina', '200 mg', 'Oral', 'Diaria', 'Tratamiento de trastornos psiquiátricos'),
('Risperidona', '1 mg', 'Oral', 'Diaria', 'Tratamiento de esquizofrenia'),
('Sitagliptina', '100 mg', 'Oral', 'Diaria', 'Control de diabetes tipo 2'),
('Topiramato', '50 mg', 'Oral', 'Diaria', 'Tratamiento de epilepsia'),
('Valproato', '500 mg', 'Oral', 'Diaria', 'Tratamiento de epilepsia'),
('Warfarina', '5 mg', 'Oral', 'Diaria', 'Anticoagulante'),
('Xarelto', '20 mg', 'Oral', 'Diaria', 'Anticoagulante'),
('Zolpidem', '10 mg', 'Oral', 'Antes de dormir', 'Tratamiento del insomnio'),
('Aciclovir', '400 mg', 'Oral', 'Diaria', 'Tratamiento de infecciones virales'),
('Amitriptilina', '25 mg', 'Oral', 'Diaria', 'Antidepresivo'),
('Bromuro de ipratropio', '20 mcg', 'Inhalación', 'Diaria', 'Tratamiento del asma'),
('Clonidina', '0.1 mg', 'Oral', 'Diaria', 'Tratamiento de la hipertensión'),
('Diclofenaco', '50 mg', 'Oral', 'Cada 8 horas', 'Antiinflamatorio no esteroideo'),
('Enalapril', '10 mg', 'Oral', 'Diaria', 'Tratamiento de la hipertensión'),
('Fentolamina', '5 mg', 'Intravenosa', 'Cada 4 horas', 'Antihipertensivo'),
('Glibenclamida', '5 mg', 'Oral', 'Diaria', 'Control de diabetes tipo 2'),
('Haloperidol', '5 mg', 'Oral', 'Diaria', 'Tratamiento de psicosis'),
('Isosorbide dinitrato', '5 mg', 'Oral', 'Diaria', 'Tratamiento de angina de pecho'),
('Ketorolaco', '30 mg', 'Intravenosa', 'Cada 6 horas', 'Analgésico para dolor severo'),
('Lisinopril', '10 mg', 'Oral', 'Diaria', 'Tratamiento de la hipertensión'),
('Morfina', '10 mg', 'Oral', 'Cada 4 horas', 'Analgésico opioide'),
('Naproxeno', '500 mg', 'Oral', 'Cada 12 horas', 'Antiinflamatorio no esteroideo'),
('Oxycodona', '10 mg', 'Oral', 'Cada 12 horas', 'Analgésico opioide'),
('Paracetamol', '500 mg', 'Oral', 'Cada 6 horas', 'Analgésico y antipirético'),
('Quetiapina', '200 mg', 'Oral', 'Diaria', 'Tratamiento de trastornos psiquiátricos'),
('Rizatriptán', '10 mg', 'Oral', 'Según necesidad', 'Tratamiento de migrañas'),
('Simvastatina', '40 mg', 'Oral', 'Diaria', 'Control de colesterol'),
('Tramadol', '50 mg', 'Oral', 'Cada 6 horas', 'Analgésico para dolor moderado'),
('Uricosuricos', '200 mg', 'Oral', 'Diaria', 'Tratamiento de gota'),
('Venlafaxina', '75 mg', 'Oral', 'Diaria', 'Tratamiento de depresión y ansiedad'),
('Warfarina', '5 mg', 'Oral', 'Diaria', 'Anticoagulante para prevención de trombosis'),
('Xanax', '0.25 mg', 'Oral', 'Diaria', 'Tratamiento de ansiedad'),
('Zolpidem', '10 mg', 'Oral', 'Antes de dormir', 'Tratamiento del insomnio'),
('Amitriptilina', '25 mg', 'Oral', 'Diaria', 'Antidepresivo'),
('Buspirona', '10 mg', 'Oral', 'Diaria', 'Tratamiento de la ansiedad'),
('Clobazam', '10 mg', 'Oral', 'Diaria', 'Tratamiento de epilepsia'),
('Duloxetina', '60 mg', 'Oral', 'Diaria', 'Tratamiento de depresión y ansiedad'),
('Escitalopram', '10 mg', 'Oral', 'Diaria', 'Antidepresivo'),
('Fluoxetina', '20 mg', 'Oral', 'Diaria', 'Antidepresivo'),
('Gliclazida', '80 mg', 'Oral', 'Diaria', 'Control de diabetes tipo 2'),
('Hydroxyzine', '25 mg', 'Oral', 'Diaria', 'Tratamiento de ansiedad y alergias'),
('Ibuprofeno', '400 mg', 'Oral', 'Cada 8 horas', 'Antiinflamatorio no esteroideo'),
('Liraglutida', '1.2 mg', 'Inyección', 'Diaria', 'Control de diabetes tipo 2'),
('Metformina', '500 mg', 'Oral', 'Diaria', 'Control de diabetes tipo 2'),
('Nabumetona', '750 mg', 'Oral', 'Diaria', 'Antiinflamatorio no esteroideo'),
('Olanzapina', '10 mg', 'Oral', 'Diaria', 'Tratamiento de esquizofrenia'),
('Pantoprazol', '40 mg', 'Oral', 'Diaria', 'Tratamiento de enfermedades gástricas'),
('Quetiapina', '200 mg', 'Oral', 'Diaria', 'Tratamiento de trastornos psiquiátricos'),
('Rivastigmina', '1.5 mg', 'Oral', 'Diaria', 'Tratamiento de Alzheimer'),
('Salmeterol', '50 mcg', 'Inhalación', 'Diaria', 'Tratamiento del asma'),
('Topiramato', '50 mg', 'Oral', 'Diaria', 'Tratamiento de epilepsia'),
('Urokinasa', '250,000 U', 'Intravenosa', 'Una vez', 'Tratamiento de embolia pulmonar'),
('Venlafaxina', '75 mg', 'Oral', 'Diaria', 'Tratamiento de depresión y ansiedad'),
('Warfarina', '5 mg', 'Oral', 'Diaria', 'Anticoagulante'),
('Xarelto', '20 mg', 'Oral', 'Diaria', 'Anticoagulante'),
('Zolpidem', '10 mg', 'Oral', 'Antes de dormir', 'Tratamiento del insomnio');
