
-- Inserción de datos en la tabla SERVICIO_HOSPITALARIO
INSERT INTO SERVICIO_HOSPITALARIO (Nombre) VALUES
('Obstetricia'),
('Ginecología'),
('Pediatría'),
('Medicina Interna'),
('Cirugía General'),
('Traumatología'),
('Oncología'),
('Cardiología'),
('Neumología'),
('Dermatología'),
('Oftalmología'),
('Otorrinolaringología'),
('Psiquiatría'),
('Neurología'),
('Anestesiología'),
('Rehabilitación'),
('Medicina Familiar'),
('Emergencia'),
('Salud Mental'),
('Endocrinología'),
('Infectología'),
('Geriatría'),
('Medicina Preventiva'),
('Laboratorio Clínico'),
('Radiología'),
('Banco de Sangre'),
('Urología'),
('Dermatología Quirúrgica'),
('Salud Pública'),
('Nefrología');
