
-- Inserción de datos en la tabla TIPO_PRUEBA relacionados con Ginecología y Obstetricia
INSERT INTO TIPO_PRUEBA (NombreTipo) VALUES
('Prueba de Embarazo'),
('Citología Cervical (Papanicolaou)'),
('Ultrasonido Obstétrico'),
('Prueba de Glucosa en Sangre'),
('Prueba de VIH'),
('Análisis de Hormonas'),
('Cultivo Vaginal'),
('Hemograma Completo'),
('Prueba de Anticuerpos Antinucleares'),
('Perfil Lipídico'),
('Prueba de Hepatitis B'),
('Prueba de Chlamydia'),
('Prueba de Gonorrea'),
('Prueba de Grupo Sanguíneo'),
('Prueba de Infecciones de Transmisión Sexual (ITS)'),
('Ultrasonido Transvaginal'),
('Prueba de Próstata'),
('Análisis de Sangre para Marcadores Tumorales'),
('Test de Ovulación'),
('Prueba de Fertilidad Masculina'),
('Perfil Hormonal Femenino'),
('Ecografía Doppler'),
('Biopsia Endometrial'),
('Prueba de VIH-SIDA'),
('Análisis de Secreciones Vaginales'),
('Detección de Embarazo Ectópico'),
('Examen de Fluido Amniótico'),
('Ultrasonido de 20 Semanas'),
('Test de Estimulación con Clomifeno'),
('Prueba de Candidiasis'),
('Examen de Papanicolaou con HPV'),
('Prueba de Listeria'),
('Prueba de Toxoplasmosis'),
('Prueba de Rubéola'),
('Prueba de Herpes Simple'),
('Cultivo de Muestras Biológicas'),
('Prueba de Anticuerpos de Covid-19'),
('Prueba de Sífilis (VDRL)'),
('Prueba de Hemoglobina'),
('Prueba de Leucemia'),
('Prueba de Virus del Papiloma Humano (VPH)'),
('Análisis de Orina con Cultivo'),
('Ecografía 3D/4D'),
('Prueba de Diabetes Gestacional'),
('Exámenes de Laboratorio de Fertilidad'),
('Detección de Infecciones Bacterianas'),
('Análisis Genético Prenatal'),
('Prueba de Mareo por Embarazo'),
('Estudio de SANGRE en Ginecología'),
('Prueba de Lactosa'),
('Prueba de Tiroides'),
('Biopsia de Ovario'),
('Ultrasonido de Saco Gestacional'),
('Estudio del Líquido Amniótico'),
('Análisis de Espermatozoides'),
('Prueba de Anticuerpos de Células Rojo');
